# this calculates the catch per pot, both large and alls using the proportion from the existing querry. 

SELECT
DATA_POT_PERFORMANCE_PWS_SPOTS.Year,
 DATA_POT_PERFORMANCE_PWS_SPOTS.SITE_ID,
 DATA_POT_PERFORMANCE_PWS_SPOTS.STATION,
 DATA_POT_PERFORMANCE_PWS_SPOTS.EVENT_ID,
 DATA_POT_PERFORMANCE_PWS_SPOTS.POT_ID,
 DATA_POT_PERFORMANCE_PWS_SPOTS.SAMPLE_POT,
 
 NZ(totByPot.SumOfSAMPLE_WEIGHT_KG,0) AS totWt,
 NZ(Q_CPUE_14.Prop_Lg_by_Wt,0) AS Prop_Lg_by_Wt,
 NZ([totWt]*[Prop_Lg_by_Wt],0) AS lrgWt,

 NZ(totByPot.SumOfCOUNT,0) AS totCt,
 NZ(Q_CPUE_14.Prop_Lg_by_Ct,0) AS Prop_Lg_by_Ct,
 NZ([totCt]*[Prop_Lg_by_Ct],0) AS lrgCt

 FROM Q_CPUE_14 RIGHT JOIN (totByPot RIGHT JOIN DATA_POT_PERFORMANCE_PWS_SPOTS ON (totByPot.EVENT_ID = DATA_POT_PERFORMANCE_PWS_SPOTS.EVENT_ID)
 AND (totByPot.POT_ID = DATA_POT_PERFORMANCE_PWS_SPOTS.POT_ID)) ON (Q_CPUE_14.SITE_ID = DATA_POT_PERFORMANCE_PWS_SPOTS.SITE_ID)
 AND (Q_CPUE_14.Year = DATA_POT_PERFORMANCE_PWS_SPOTS.YEAR)

 WHERE (((DATA_POT_PERFORMANCE_PWS_SPOTS.STATION) Not In ("E","E1","E2")) AND 
		(DATA_POT_PERFORMANCE_PWS_SPOTS.FK_GEAR_PERFORMANCE_CODE = '01'));

