# This is copy of CPUE_4 with addition of grouping by POT_ID, adding EVENT_ID and changeing from create table to select. 

SELECT
 DATA_CATCHCOMP_PWS_SPOTS.Year,
 DATA_CATCHCOMP_PWS_SPOTS.SITE_ID,
 DATA_CATCHCOMP_PWS_SPOTS.STATION_ID,
 DATA_CATCHCOMP_PWS_SPOTS.EVENT_ID,
 DATA_CATCHCOMP_PWS_SPOTS.POT_ID,
 DATA_CATCHCOMP_PWS_SPOTS.FK_GEAR_PERFORMANCE_CODE,
 DATA_CATCHCOMP_PWS_SPOTS.FK_SPECIES_CODE,
 DATA_CATCHCOMP_PWS_SPOTS.CONDITION_CODE,
 Sum(DATA_CATCHCOMP_PWS_SPOTS.Count) AS SumOfCOUNT,
 Sum(DATA_CATCHCOMP_PWS_SPOTS.SAMPLE_WEIGHT_KG) AS SumOfSAMPLE_WEIGHT_KG

FROM DATA_CATCHCOMP_PWS_SPOTS

GROUP BY
 DATA_CATCHCOMP_PWS_SPOTS.Year,
 DATA_CATCHCOMP_PWS_SPOTS.SITE_ID,
 DATA_CATCHCOMP_PWS_SPOTS.STATION_ID,
 DATA_CATCHCOMP_PWS_SPOTS.EVENT_ID,
 DATA_CATCHCOMP_PWS_SPOTS.POT_ID,
 DATA_CATCHCOMP_PWS_SPOTS.FK_GEAR_PERFORMANCE_CODE,
 DATA_CATCHCOMP_PWS_SPOTS.FK_SPECIES_CODE,
 DATA_CATCHCOMP_PWS_SPOTS.CONDITION_CODE
 

 HAVING (((
 DATA_CATCHCOMP_PWS_SPOTS.Year)>"1991")
 AND ((DATA_CATCHCOMP_PWS_SPOTS.STATION_ID) Not In ("E","E1","E2"))
 AND ((DATA_CATCHCOMP_PWS_SPOTS.FK_SPECIES_CODE)="965")
 AND ((DATA_CATCHCOMP_PWS_SPOTS.CONDITION_CODE)="01")
 AND ((DATA_CATCHCOMP_PWS_SPOTS.FK_GEAR_PERFORMANCE_CODE)="01"))


 ORDER BY

 DATA_CATCHCOMP_PWS_SPOTS.Year,
 DATA_CATCHCOMP_PWS_SPOTS.SITE_ID,
 DATA_CATCHCOMP_PWS_SPOTS.STATION_ID;
