SELECT 
	DATA_AWL_SHELLFISH_PWS_SPOT_SURVEY.*
INTO
tempAwlSel
FROM DATA_POT_PERFORMANCE_PWS_SPOTS
	INNER JOIN DATA_AWL_SHELLFISH_PWS_SPOT_SURVEY 
	ON (DATA_POT_PERFORMANCE_PWS_SPOTS.POT_ID = DATA_AWL_SHELLFISH_PWS_SPOT_SURVEY.POT_ID) 
	AND (DATA_POT_PERFORMANCE_PWS_SPOTS.EVENT_ID = DATA_AWL_SHELLFISH_PWS_SPOT_SURVEY.EVENT_ID)
WHERE DATA_POT_PERFORMANCE_PWS_SPOTS.STATION Not In ("E","E1","E2") 
	AND DATA_POT_PERFORMANCE_PWS_SPOTS.FK_GEAR_PERFORMANCE_CODE = "01"	;
